version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@3.2

commands:
  build-image: aws-ecr/build-image

workflows:
  deploy-to-development:
    jobs:
      - aws-ecr/build-and-push-image:
          name: "build-and-push-image"
          context:
            - PEAKSOFT_HOUSE_FRONTEND_GLOBAL_AWS_CONTEXT
          account-url: DEV_AWS_ECR_ACCOUNT_URL
          create-repo: false
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          region: AWS_DEFAULT_REGION
          repo: $DEV_AWS_ECR_REPO_NAME
          skip-when-tags-exist: false
          tag: $CIRCLE_SHA1
          filters:
            branches:
              only:
                - development
      - aws-ecs/deploy-service-update:
          name: "deploy-service-update"
          context:
            - PEAKSOFT_HOUSE_FRONTEND_GLOBAL_AWS_CONTEXT
          cluster: $CLUSTER_NAME
          container-image-name-updates: 'container=${DEV_CONTAINER_NAME},tag=${CIRCLE_SHA1}'
          family: $DEV_TASK_NAME
          service-name: $DEV_SERVICE_NAME
          force-new-deployment: true
          requires:
            - build-and-push-image
          filters:
            branches:
              only:
                - development
