// import { useEffect } from 'react'
// import { useDispatch } from 'react-redux'
// import Head from 'next/head'
// import NavBar from '../components/navBar/NavBar'
// import Whatsapp from '../components/whatsapp/Whatsapp'
// import Footer from '../components/footer/Footer'
// import CompLiteracyHeader from '../components/compLiteracy/compLiteracyHeader/CompLiteracyHeader'
// import { baseFetch } from '../api/baseFetch'
// import { generalActions } from '../store/generalSlice'

// const CompLiteracy = ({ courseType, banners }) => {
//    const dispath = useDispatch()
//    useEffect(() => {
//       dispath(
//          generalActions.getServerData({
//             courseType,
//             banners,
//          })
//       )
//    }, [courseType, banners])
//    return (
//       <div>
//          <Head>
//             <title>Computer Literacy</title>
//             <meta name="description" content="Generated by create next app" />
//             <link rel="icon" href="/favicon.ico" />
//             <meta
//                name="viewport"
//                content="width=device-width, initial-scale=1.0, user-scalable=yes"
//             />
//          </Head>
//          <main>
//             <div>
//                <div id="modal" />
//                <NavBar page="false" />
// {
/* <CompLiteracyHeader /> */
// }
//                <Footer />
//                <Whatsapp />
//             </div>
//          </main>
//       </div>
//    )
// }

// export default CompLiteracy

// export async function getServerSideProps() {
//    const getStaticData = {
//       courseType: null,
//       error: null,
//       banners: null,
// infoBanners: null,
// courseTypeConsultation: null,
// }
// try {
//    const courseTypeResponse = await baseFetch({
//       method: 'GET',
//       path: 'offices/2/course-types',
//    })
// courseTypes?getCourseType=CONSULTATION
// const consultationType = await baseFetch({
//    method: 'GET',
//    path: 'courseTypes?getCourseType=CONSULTATION',
// })
// const registrationBanners = await baseFetch({
//    method: 'GET',
//    path: 'banners/office/2',
// })
// const infoBanners = await baseFetch({
//    method: 'GET',
//    path: 'banners/find/info-banners2?active=true',
// })
// getStaticData.courseTypeConsultation = await consultationType
// getStaticData.infoBanners = await infoBanners
//    getStaticData.banners = await registrationBanners
//    getStaticData.courseType = await courseTypeResponse
// } catch (error) {
//    getStaticData.error = error.message
// }
// return {
//    props: getStaticData,
// }
// }
