import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { generalActions } from '../store/generalSlice'
import Employment from '../components/employment/Employment'
import NavBar from '../components/navBar/NavBar'
import Whatsapp from '../components/whatsapp/Whatsapp'
import { baseFetch } from '../api/baseFetch'

export default function Job({ courseTypeConsultation }) {
   const dispatch = useDispatch()

   useEffect(() => {
      dispatch(generalActions.getConsultation(courseTypeConsultation))
   }, [courseTypeConsultation])
   return (
      <div>
         <Head>
            <title>Job Page</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1.0, user-scalable=yes"
            />
         </Head>
         <main>
            <div id="modal" />
            <NavBar page="false" />
            <Employment />
            <Whatsapp />
         </main>
      </div>
   )
}

export async function getServerSideProps() {
   const getStaticData = {
      courseTypeConsultation: null,
   }
   try {
      const consultationType = await baseFetch({
         method: 'GET',
         path: 'courseTypes?getCourseType=CONSULTATION',
      })

      getStaticData.courseTypeConsultation = await consultationType
   } catch (error) {
      getStaticData.error = error.message
   }
   return {
      props: getStaticData,
   }
}
